### ISSUE TITLE
Add links to a new (statewide?) AGOL map that has geographies for items in viz tool picklists (polygons like (small areas), lines (routes), points (stations))

### ISSUE THREAD

**Issue by bert-granberg** [WFRCAnalytics/vizTool#12]
Could go to the right of the checklist header as something as simple as 'map'...maybe just the geographies that are mostly static across the scenarios --  (polygons like small areas, maybe route lines, maybe station points).

**Comment by bhereth** [comment]
Reference map popup has been added.
